#############################################################
# 메타생성
# --mode=info
#############################################################
source: "" # 직접수정
# target이 빈값이면 info.xml / cover.jpg만 생성
target: "" 
# 메뉴 no meta 선택시 이동할 폴더
no_meta_target: ""

# 가, 나, 다 사용여부
use_cate: true

# 커버 생성 여부
cover: true

# 자동처리 여부 0:off 1:semi_auto 2:auto
semi_auto: 0

# 메타 소스 3개 중 하나
meta_source: "kakaopage" # naverbook, naverseries, kakaopage ,kakaobook ,ridi, ridibook

# naverbook 으로 검색시 apikey 필요
naver_api_key:
  - ''
  #- 'bbbbbbbbbbbbbbbbbbbbbbbbbbb'

# kakaobook 으로 검색시 apikey 필요
kakao_api_key:  
  - ''




#############################################################
# text2epub
# --mode=epub
#############################################################
text2epub:
  # 탐색할 소스폴더. 각 폴더 안에는 cover.jpg / info.xml이 있어야 한다.
  source_folderpath: ""

  # txt 파일에 따라 내용 한줄당 빈줄이 하나씩 들어가는 경우도 있고 내용 한줄 - 빈줄 2줄인 경우도 있다.
  # 이 빈줄을 모두 epub에 빈줄로 넣지 않으려면 이 값을 조정한다.
  # 값이 2인 경우 txt에 빈줄이 2개 있으면 epub에 한줄을 넣는다.
  EPUB_빈줄비율: 3

  # html 페이지당 넣을 txt파일 라인수
  HTML줄수: 1000
  






























# 소주 전용

텍스트 이동: "/host/mnt/etc1/MP/Book/웹소설/[텍스트]"
#############################################################
upload_source: "/host/mnt/etc1/ETC2/upload/리딩"
#############################################################
web_source: "/host/mnt/etc1/MP2/책/웹_source"
web_target: "/host/mnt/etc1/MP2/책/웹소설"
